#!/bin/bash
echo ""
echo "Installing PVSNESLIB in current folder"
echo ""

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`
tail -n+$ARCHIVE $0 | tar xzv -C $PWD
exit 0

__ARCHIVE_BELOW__
